apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rabbitping.fullname" . }}
  namespace: {{ .Values.configMapProperties.RESTART_NAMESPACE }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rabbitping.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "rabbitping.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
